sudo: required

dist: xenial

language: node_js
node_js:
  - "node"

branches:
  only:
    - source

before_script:
  - cd website
  - npm install
  - npm run nuxt-generate --verbose

#https://caveofcode.com/2017/05/publish-an-angular-app-to-github-pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: website/dist
  on:
    branch: source
  target-branch: master
