#sudo: required
#dist: xenial

os:
 - osx

language: node_js
node_js:
  - "node"

branches:
  only:
    - source

before_install:
  - brew update
  - brew upgrade python

install: true

script:  
  - python3 --version
  - pip3 install --upgrade pip
  - pip3 install -r website/scripts/python-requirements.txt
  - python3 website/scripts/create_blog_metadata.py
  - cd website
  - npm install
  - npm run nuxt-generate --verbose
  - cd ..

#https://caveofcode.com/2017/05/publish-an-angular-app-to-github-pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: website/dist
  on:
    branch: source
  target-branch: master
