# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

defaults: &defaults
  working_directory: /tmp

version: 2
jobs:  
  generate_blog_metadata: # python script
    <<: *defaults
    docker:      
      - image: circleci/python:3.7.2

    working_directory: ~/repo
        
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo/tmp

      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install -r website/scripts/python-requirements.txt
            python3 website/scripts/create_blog_metadata.py
            mkdir -p tmp/
            cp website/src/static/blogdata tmp -r
            find tmp
      
      - persist_to_workspace:
          root: tmp
          paths: 
            - blogdata
      
  generate_website: # node
    <<: *defaults
    docker:      
      - image: circleci/node:11.13.0

    working_directory: ~/repo
        
    steps:
      - checkout

      - attach_workspace:
          at: ~/repo/tmp

      - run:
          command: |
            find tmp
            cp tmp/blogdata website/src/static/ -r
            cd website
            npm install
            sudo npm run nuxt-generate --verbose
            cd .. 
            find website/dist

workflows:
  version: 2
  build:
    jobs:
      - generate_blog_metadata:        
          filters:
            branches:
              only:
                - source
      - generate_website:        
          filters:
            branches:
              only:
                - source
          requires:
            - generate_blog_metadata