# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

defaults: &defaults
  working_directory: /tmp

version: 2.1
jobs:
  generate_blog_metadata: # python script
    <<: *defaults
    docker:
      - image: circleci/python:3.9.6

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo/tmp

      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install -r website/scripts/python-requirements.txt
            python3 website/scripts/create_blog_metadata.py
            mkdir -p tmp/
            cp website/static/blogdata tmp -r
            find tmp

      - persist_to_workspace:
          root: tmp
          paths:
            - blogdata

  generate_website: # node
    <<: *defaults
    docker:
      - image: circleci/node:16.5.0

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo/tmp

      - run:
          name: Run npm generate
          command: |
            cp tmp/blogdata website/static/blogdata -r
            cd website
            npm install --legacy-peer-deps
            npm run getHighlightJsStyleSheets
            sudo npm run generate
            cd ..
            cp website/dist tmp -r

      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g --silent gh-pages@2.0.1
            sudo git config user.email "manas.talukdar@gmail.com"
            sudo git config user.name "circle-ci-build"

      - add_ssh_keys:
          fingerprints:
            - "5e:7e:51:39:c2:4e:ee:84:0f:1d:e5:4d:4a:f6:6e:7f"

      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --dist tmp/dist --branch main --message "Circle CI Updates [ci skip]"

workflows:
  build:
    jobs:
      - generate_blog_metadata:
          filters:
            branches:
              only:
                - source
      # - generate_website:
      #     filters:
      #       branches:
      #         only:
      #           - source
      #     requires:
      #       - generate_blog_metadata
