name: build-deploy
on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source
  workflow_dispatch:
jobs:
  build:
    name: Build, Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Extract Branch Name
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: "x64"
      - run: python --version
      - run: pip install -r website/scripts/python-requirements.txt
      - run: python website/scripts/create_blog_metadata.py
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: node --version
      - run: npm --version
      - working-directory: website
        run: npm install
      - working-directory: website
        run: npm run getHighlightJsStyleSheets
      - working-directory: website
        run: npm run generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && env.BRANCH == 'source' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/.output/public
          publish_branch: main # default: gh-pages
          keep_files: false # default: false
          force_orphan: true
          commit_message: "GitHub CI Updates [ci skip]"
