name: build-deploy
on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source
jobs:
  build:
    name: Build, Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"
      - run: python --version
      - run: pip install -r website/scripts/python-requirements.txt
      - run: python website/scripts/create_blog_metadata.py
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: node --version
      - working-directory: website
        run: npm install
      - working-directory: website
        run: npm run getHighlightJsStyleSheets
      - working-directory: website
        run: sudo npm run static
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist
          publish_branch:  master  # default: gh-pages
          keep_files: false # default: false
          commit_message: "GitHub CI Updates [ci skip]"
